import { chromium } from "playwright";
const OUT="C:/Users/elyas/Downloads/Claude_Website_MEC/shots";
const b = await chromium.launch();
const p = await (await b.newContext({viewport:{width:1440,height:900}})).newPage();
await p.goto("http://localhost:3000/",{waitUntil:"networkidle"});
await p.evaluate(()=>{const h2=[...document.querySelectorAll("h2")].find(h=>h.textContent?.includes("to your kitchen")); h2?.closest("section")?.scrollIntoView({block:"center"});});
await new Promise(r=>setTimeout(r,4000));
await p.screenshot({path:`${OUT}/fix2-map.png`});
const map = await p.$("div.max-w-4xl");
if(map) await map.screenshot({path:`${OUT}/fix2-mapcrop.png`});
await b.close(); console.log("done");
