import { chromium } from "playwright";
const OUT="C:/Users/elyas/Downloads/Claude_Website_MEC/shots";
const b = await chromium.launch();
const m = await (await b.newContext({viewport:{width:390,height:844}, deviceScaleFactor:2, isMobile:true})).newPage();
await m.goto("http://localhost:3000/",{waitUntil:"networkidle"});
await new Promise(r=>setTimeout(r,2500));
const overflow = await m.evaluate(()=>({sw:document.documentElement.scrollWidth, iw:window.innerWidth}));
console.log("scrollWidth", overflow.sw, "innerWidth", overflow.iw, overflow.sw>overflow.iw+1 ? "OVERFLOW!" : "OK no h-scroll");
await m.evaluate(()=>{const h2=[...document.querySelectorAll("h2")].find(h=>h.textContent?.includes("to your kitchen")); h2?.closest("section")?.scrollIntoView({block:"start"});});
await new Promise(r=>setTimeout(r,3000));
await m.screenshot({path:`${OUT}/m-map-fixed.png`});
await b.close();
